### ISSUE TITLE
sperf doesn't find find dse, cassandra, solr, spark version

### ISSUE THREAD

**Issue by thatran** [riptano/sperf#3]
sperf doesn't find find dse, cassandra, solr, spark version
because it only looks for that info in the output.log files,
but we get a lot of diag tarballs that don't have output.log files in them.  In this case, sperf could search in system.log for the version info (if there was a dse restart not long ago, the version info can be found in system.log)

**Comment by rssvihla** [comment]
It already does this it is just looking for a specific log format from the system and output logs (everything after the -) and so will not match all types of logs that are "DSE version" as all of those have not been vetted.
Example log that does work from system.log when no output log is present:

INFO  [main] 2020-01-10 16:18:44,252  DseDaemon.java:510 - Spark version: 2.2.3.9

**Comment by rssvihla** [comment]
missing example log
